swagger: '2.0'
info:
  description: |
    This API is used for order detail query

    <SDKLinks module="trade" klass="TradeContext" method="order_detail" />
  version: 'v1'
  title: 'Order Details'
paths:
  /v1/trade/order:
    get:
      access: 'Trading Permissions'
      parameters:
        - name: 'order_id'
          type: 'string'
          description: 'Order ID for specifying order ID query, for example: `701276261045858304`'
          required: true
      responses:
        '200':
          description: 'Order detail query successful'
          schema:
            $ref: '#/definitions/order_detail_rsp'
        '400':
          description: 'Query failed, request parameter error.'
      request_body:
        type: 'python'
        value: |
          from longport.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)

          resp = ctx.order_detail(
              order_id = "701276261045858304",
          )
          print(resp)
      response_body:
        {
          'code': 0,
          'message': 'success',
          'data':
            {
              'order_id': '828940451093708800',
              'status': 'FilledStatus',
              'stock_name': 'Apple',
              'quantity': '10',
              'executed_quantity': '10',
              'price': '200.000',
              'executed_price': '164.660',
              'submitted_at': '1680863604',
              'side': 'Buy',
              'symbol': 'AAPL.US',
              'order_type': 'LO',
              'last_done': '164.660',
              'trigger_price': '0.0000',
              'msg': '',
              'tag': 'Normal',
              'time_in_force': 'Day',
              'expire_date': '2023-04-10',
              'updated_at': '1681113000',
              'trigger_at': '0',
              'trailing_amount': '',
              'trailing_percent': '',
              'limit_offset': '',
              'trigger_status': 'NOT_USED',
              'outside_rth': 'ANY_TIME',
              'currency': 'USD',
              'remark': '1680863603.927165',
              'free_status': 'None',
              'free_amount': '',
              'free_currency': '',
              'deductions_status': 'NONE',
              'deductions_amount': '',
              'deductions_currency': '',
              'platform_deducted_status': 'NONE',
              'platform_deducted_amount': '',
              'platform_deducted_currency': '',
              'history':
                [
                  {
                    'price': '164.6600',
                    'quantity': '10',
                    'status': 'FilledStatus',
                    'msg': 'Execution of 10',
                    'time': '1681113000',
                  },
                  { 'price': '200.0000', 'quantity': '10', 'status': 'NewStatus', 'msg': '', 'time': '1681113000' },
                ],
              'charge_detail':
                {
                  'items':
                    [
                      { 'code': 'BROKER_FEES', 'name': 'Broker Fees', 'fees': [] },
                      { 'code': 'THIRD_FEES', 'name': 'Third-party Fees', 'fees': [] },
                    ],
                  'total_amount': '0',
                  'currency': 'USD',
                },
            },
        }
definitions:
  order_detail_rsp:
    type: 'object'
    description: Order Information
    required:
      [
        'order_id',
        'status',
        'stock_name',
        'quantity',
        'executed_quantity',
        'price',
        'executed_price',
        'submitted_at',
        'side',
        'symbol',
        'order_type',
        'last_done',
        'trigger_price',
        'msg',
        'tag',
        'time_in_force',
        'expire_date',
        'updated_at',
        'trigger_at',
        'trailing_amount',
        'trailing_percent',
        'limit_offset',
        'trigger_status',
        'currency',
        'outside_rth',
        'remark',
        'free_status',
        'free_amount',
        'free_currency',
        'deductions_status',
        'deductions_amount',
        'deductions_currency',
        'platform_deducted_status',
        'platform_deducted_amount',
        'platform_deducted_currency',
        'history',
        'charge_detail',
      ]
    properties:
      order_id:
        type: 'string'
        description: Order ID
        required: true
      status:
        type: 'string'
        description: '[Order Status](../trade-definition#orderstatus)'
        required: true
      stock_name:
        type: 'string'
        description: Stock Name
        required: true
      quantity:
        type: 'string'
        description: Order Quantity
        required: true
      executed_quantity:
        type: 'string'
        description: Executed Quantity<br/><br/>When the order is not executed, it is 0
      price:
        type: 'string'
        description: Order Price<br/><br/>When the market price conditional order is not triggered, it is an empty string
        required: true
      executed_price:
        type: 'string'
        description: Execution Price<br/><br/>When the order is not executed, it is 0
      submitted_at:
        type: 'string'
        description: Submitted Time
        required: true
      side:
        type: 'string'
        description: Order Side<br/><br/>
          **Enum Value:**<br/>
          `Buy`<br/>
          `Sell`
        required: true
      symbol:
        type: 'string'
        description: 'Stock symbol, use `ticker.region` format, example: `AAPL.US`'
        required: true
      order_type:
        type: 'string'
        description: '[Order Type](../trade-definition#ordertype)'
        required: true
      last_done:
        type: 'string'
        description: Last done.<br/><br/>when the order is not filled, value is empty string
        required: true
      trigger_price:
        type: 'string'
        description: '`LIT` / `MIT` Order Trigger Price.<br/><br/>When the order is not `LIT` / `MIT` order, value is empty string'
        required: true
      msg:
        type: 'string'
        description: Rejected message or remark, default value is empty string.
        required: true
      tag:
        type: 'string'
        description: Order tag<br/><br/>
          **Enum Value**<br/>
          `Normal` - Normal Order<br/>
          `GTC` - Long term Order<br/>
          `Grey` - Grey Order
        required: true
      time_in_force:
        type: 'string'
        description: '
          Time in force Type<br/><br/>
          **Enum Value:**<br/>
          `Day` - Day Order<br/>
          `GTC` - Good Til Canceled Order<br/>
          `GTD` - Good Til Date Order'
        required: true
      expire_date:
        type: 'string'
        description: 'Long term order expire date, format: `YYYY-MM-DD`, example: `2022-12-05`.<br/><br/>
          When not a long term order, default value is empty string'
        required: true
      updated_at:
        type: 'string'
        required: true
        description: Last updated time, formatted as a timestamp (second)
      trigger_at:
        type: 'string'
        required: true
        description: Conditional order trigger time. formatted as a timestamp (second)
      trailing_amount:
        type: 'string'
        required: true
        description: '`TSLPAMT` order trailing amount.<br/><br/>When the order is not `TSLPAMT` order, value is empty string'
      trailing_percent:
        type: 'string'
        required: true
        description: '`TSLPPCT` order trailing percent.<br/><br/>When the order is not `TSLPPCT` order, value is empty string'
      limit_offset:
        type: 'string'
        required: true
        description: '`TSLPPCT` order limit offset amount.<br/><br/>When the order is not `TSLPPCT` order, value is empty string'
      trigger_status:
        type: 'string'
        required: true
        description: Conditional Order Trigger Status<br/>
          When an order is not a conditional order or a conditional order is not triggered, the trigger status is NOT_USED<br/><br/>
          **Enum Value**<br/>
          `NOT_USED`<br/>
          `DEACTIVE`<br />
          `ACTIVE`<br />
          `RELEASED`
      currency:
        type: 'string'
        description: Currency
        required: true
      outside_rth:
        type: 'string'
        required: true
        description: Enable or disable outside regular trading hours<br/>
          Default is `UnknownOutsideRth` when the order is not a US stock<br/><br/>
          **Enum Value:**<br/>
          `RTH_ONLY` - Regular trading hour only<br/>
          `ANY_TIME` - Any time<br/>
          `OVERNIGHT` - Overnight"
      remark:
        type: 'string'
        description: Remark
        required: true
      free_status:
        type: 'string'
        required: true
        description: Commission-free Status, default value is None<br/><br/>
          **Enum Value:**<br/>
          `None` - None<br/>
          `Calculated` - Commission-free amount to be calculated<br/>
          `Pending` - Pending commission-free<br/>
          `Ready` - Commission-free applied
      free_amount:
        type: 'string'
        required: true
        description: Commission-free amount, default value is empty string.
      free_currency:
        type: 'string'
        required: true
        description: Commission-free currency, default value is empty string.
      deductions_status:
        type: 'string'
        required: true
        description: Deduction status/Cashback Status, default value is NONE<br/><br/>
          **Enum Value:**<br/>
          `NONE` - Pending Settlement <br/>
          `NO_DATA` - Settled with no data<br/>
          `PENDING` - Settled and pending distribution<br/>
          `DONE` - Settled and distributed
      deductions_amount:
        type: 'string'
        required: true
        description: Deduction amount, default value is empty string.
      deductions_currency:
        type: 'string'
        required: true
        description: Deduction currency, default value is empty string.
      platform_deducted_status:
        type: 'string'
        required: true
        description: Platform fee deduction status/Cashback Status, default value is NONE<br/><br/>
          **Enum Value:**<br/>
          `NONE` - Pending Settlement <br/>
          `NO_DATA` - Settled with no data<br/>
          `PENDING` - Settled and pending distribution<br/>
          `DONE` - Settled and distributed
      platform_deducted_amount:
        type: 'string'
        required: true
        description: Platform fee deduction amount, default value is empty string.
      platform_deducted_currency:
        type: 'string'
        required: true
        description: Platform fee deduction currency, default value is empty string.
      history:
        type: 'object[]'
        description: Order history details
        required:
          - price
          - quantity
          - status
          - msg
          - time
        properties:
          price:
            type: 'string'
            description: Executed price for executed orders, submitted price for expired, canceled, rejected orders, etc.
            required: true
          quantity:
            type: 'string'
            description: Executed quantity for executed orders, remaining quantity for expired, canceled, rejected orders, etc.
            required: true
          status:
            type: 'string'
            description: Order status
            required: true
          msg:
            type: 'string'
            description: Execution or error message
            required: true
          time:
            type: 'string'
            description: Occurrence time
            required: true
      charge_detail:
        type: 'object'
        description: Order charges
        required:
          - items
          - total_amount
          - currency
        properties:
          total_amount:
            type: 'string'
            description: Total charges amount
            required: true
          currency:
            type: 'string'
            description: Settlement currency
            required: true
          items:
            type: 'object[]'
            description: Order charge details
            required:
              - code
              - name
              - fees
            properties:
              code:
                type: 'string'
                description: Charge category code<br/><br/>
                  **Enum Value:**<br/>
                  `UNKNOWN`<br/>
                  `BROKER_FEES`<br/>
                  `THIRD_FEES`
              name:
                type: 'string'
                description: Charge category name
              fees:
                type: 'object[]'
                description: Charge details
                required:
                  - code
                  - name
                  - amount
                  - currency
                properties:
                  code:
                    type: 'string'
                    description: Charge code
                    required: true
                  name:
                    type: 'string'
                    description: Charge name
                    required: true
                  amount:
                    type: 'string'
                    description: Charge amount
                    required: true
                  currency:
                    type: 'string'
                    description: Charge currency
                    required: true
