swagger: "2.0"
info:
  description: |
    This API is used to replace order, modify quantity or price.

    <SDKLinks module="trade" klass="TradeContext" method="replace_order" />
  version: "v1"
  title: "Replace Order"
paths:
  /v1/trade/order:
    put:
      access: "Trading Permissions"
      parameters:
        - name: "order_id"
          type: "string"
          description: "Order ID"
          required: true
        - name: "quantity"
          type: "string"
          description: "Replaced quantity, example: `100`"
          required: true
        - name: "price"
          required: false
          description: "Replaced price, example: `388.5`<br/><br/>
            `LO` / `ELO` / `ALO` / `ODD` / `LIT` Order Required"
        - name: trigger_price
          required: false
          description: "Trigger price, example: `388.5`<br/><br/>
            `LIT` / `MIT` Order Required"
        - name: limit_offset
          required: false
          description: Limit offset amount<br/><br/>
            `TSLPAMT` / `TSLPPCT` Order Required
        - name: trailing_amount
          required: false
          description: Trailing amount<br/><br/>
            `TSLPAMT` Order Required
        - name: trailing_percent
          required: false
          description: Trailing percent<br/><br/>
            `TSLPPCT` Order Required
        - name: remark
          required: false
          description: "Remark (Maximum 64 characters)"
      responses:
        "200":
          description: "The submission was successful and the order was commissioned."
        "400":
          description: "The replace was rejected with an incorrect request parameter."
      request_body:
        type: "python"
        value: |
          from decimal import Decimal
          from longport.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)

          ctx.replace_order(
              order_id = "709043056541253632",
              quantity = Decimal(100),
              price = Decimal(50),
          )
      response_body: { "code": 0, "message": "success", "data": {} }
