swagger: "2.0"
info:
  description: "更新關註分組"
  version: "v1"
  title: "更新關註分組"
paths:
  /v1/watchlist/groups:
    put:
      access:
      parameters:
        - name: "id"
          type: "integer"
          in: body
          description: "分組 ID"
          required: true
        - name: "name"
          type: "string"
          in: body
          description: "分組名稱。不傳遞則不更新。"
          required: false
        - name: "securities"
          type: "string[]"
          in: body
          description: "分組下的股票列表。不傳遞則不更新。列表中的順序將作為展示順序。分組中不在此列表中的股票將被移除關註"
          required: false

      responses:
        "200":
          description: "返回成功"
        "500":
          description: "內部錯誤"
      request_body:
        type: "python"
        value: |

      response_body: { "code": 0 }
