swagger: '2.0'
info:
  description: |
    The API is used to obtain capital inflow/outflow direction, capital type, capital amount, occurrence time,
    associated stock code and capital flow description information.

    <SDKLinks module="trade" klass="TradeContext" method="cash_flow" />
  version: 'v1'
  title: 'Get Cash Flow'
paths:
  /v1/asset/cashflow:
    get:
      access:
      parameters:
        - name: 'start_time'
          type: 'string'
          description: 'start time timestamp, in `seconds`, E.g:`1650037563`'
          required: true
        - name: 'end_time'
          type: 'string'
          description: 'end time timestamp, in `seconds`, E.g:`1650747581`'
          required: true
        - name: 'business_type'
          type: 'string'
          description: 'Balance type<br/><br/> <b>Option:</b> <br/>`1` - cash <br/>`2` - stock<br/> `3` - fund'
          required: false
        - name: 'symbol'
          type: 'string'
          description: 'Target code, E.g:`AAPL.US`'
          required: false
        - name: 'page'
          type: 'string'
          description: 'start page <br/><br/><b>Default value:</b> `1`  <br/><b>Data validation rules:</b><br/> <b>Ranges:</b> `>=1`'
          required: false
        - name: 'size'
          type: 'string'
          description: 'page size <br/><br/><b>Default value:</b> `50` <br/><b>Data validation rules:</b> `1~10000`'
          required: false

      responses:
        '200':
          description: 'Success'
          schema:
            $ref: '#/definitions/cashflow_rsp'
        '400':
          description: 'Internal Error'
      request_body:
        type: 'python'
        value: |
          # Get Cash Flow
          # https://open.longportapp.com/docs/trade/asset/cashflow
          from datetime import datetime
          from longport.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)
          resp = ctx.cash_flow(
              start_at = datetime(2022, 5, 9),
              end_at = datetime(2022, 5, 12),
          )
          print(resp)
      response_body:
        {
          'code': 0,
          'data':
            {
              'list':
                [
                  {
                    'transaction_flow_name': 'BuyContract-Stocks',
                    'direction': 1,
                    'balance': '-248.60',
                    'currency': 'USD',
                    'business_time': '1621507957',
                    'symbol': 'AAPL.US',
                    'description': 'AAPL',
                  },
                  {
                    'transaction_flow_name': 'BuyContract-Stocks',
                    'direction': 1,
                    'balance': '-125.16',
                    'currency': 'USD',
                    'business_time': '1621504824',
                    'symbol': 'AAPL.US',
                    'description': 'AAPL',
                  },
                ],
            },
        }

definitions:
  cashflow_rsp:
    properties:
      list:
        type: 'object[]'
        description: Cash flow info
        required:
          - transaction_flow_name
          - direction
          - business_type
          - balance
          - currency
          - business_time
        properties:
          transaction_flow_name:
            type: string
            description: Cash flow name
            required: true
          direction:
            type: 'string'
            description: outflow direction <br/><br/><b>Option:</b> <br/>`1` - outflow <br/>  `2` - inflow
            required: true
          business_type:
            type: 'string'
            required: true
            description: Funding Category <br/><br/><b>Option:</b> <br/>`1` - cash <br/> `2` - stock <br/> `3` - fund
          balance:
            type: 'string'
            description: Cash amount
            required: true
          currency:
            type: 'string'
            description: Cash Currency
            required: true
          business_time:
            type: 'string'
            description: business time
            required: true
          symbol:
            type: 'string'
            description: associated Stock code information
          description:
            type: 'string'
            description: Cash flow description
