swagger: '2.0'
info:
  description: |
    This API is used to obtain the initial margin ratio, maintain the margin ratio and strengthen the
    margin ratio of stocks.

    <SDKLinks module="trade" klass="TradeContext" method="margin_ratio" />
  version: 'v1'
  title: 'Get margin ratio'
paths:
  /v1/risk/margin-ratio:
    get:
      access:
      parameters:
        - name: 'symbol'
          type: 'string'
          description: 'Stock symbol, using the format `ticker.region`, for example: `AAPL.US`'
          required: true
      responses:
        '200':
          description: 'Success'
          schema:
            $ref: '#/definitions/margin_ratio_rsp'
        '400':
          description: 'Internal Error'
      request_body:
        type: 'python'
        value: |
          from datetime import datetime
          from longport.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)
          resp = ctx.margin_ratio("700.HK")
          print(resp)
      response_body: { 'code': 0, 'data': { 'im_factor': '0.1', 'mm_factor': '0.1', 'fm_factor': '0.1' } }

definitions:
  margin_ratio_rsp:
    required:
      - im_factor
      - mm_factor
      - fm_factor
    properties:
      im_factor:
        type: 'string'
        description: Initial margin ratio
        required: true
      mm_factor:
        type: 'string'
        description: Maintain the initial margin ratio
        required: true
      fm_factor:
        type: 'string'
        description: Forced close-out margin ratio
        required: true
