swagger: "2.0"
info:
  description: "The API is used to obtain stock position information including account, stock code, number of shares held, number of available shares, average position price (calculated according to account settings), and currency."
  version: "v1"
  title: "Get Stock Positions"
paths:
  /v1/asset/stock:
    get:
      access:
      parameters:
        - name: "symbol"
          type: "string[]"
          description: "Stock code，use `ticker.region` format，E.g：`AAPL.US`"
          required: false
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/stock_rsp"
        "202001":
          description: "Internal Error"
        "202201":
          description: "Failed to obtain user information, check whether the account binding association is correct"
        "202202":
          description: "Parameter error, check whether the parameters are inconsistent with the requirements"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import Auth, Config, HttpClient
            auth = Auth("${APP_KEY}", "${APP_SECRET}", "${ACCESS_TOKEN}")
            config = Config(base_url = "https://openapi.longbridge.global")
            client = HttpClient(auth, config)
            result = client.get("/v1/asset/stock")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "stock_info":
                      [
                        {
                          "symbol": "700.HK",
                          "symbol_name": "TENCENT",
                          "currency": "HK",
                          "quality": "650",
                          "available_quality": "-450",
                          "cost_price": "457.53",
                        },
                        {
                          "symbol": "9991.HK",
                          "symbol_name": "BAOZUN-SW",
                          "currency": "HK",
                          "quality": "200",
                          "available_quality": "0",
                          "cost_price": "32.25",
                        },
                        {
                          "symbol": "TCEHY.US",
                          "symbol_name": "Tencent (ADR)",
                          "currency": "US",
                          "quality": "10",
                          "available_quality": "10",
                        },
                        {
                          "symbol": "2628.HK",
                          "symbol_name": "CHINA LIFE",
                          "currency": "HK",
                          "quality": "9000",
                          "available_quality": "0",
                        },
                        {
                          "symbol": "5.HK",
                          "symbol_name": "HSBC HOLDINGS",
                          "currency": "HK",
                          "quality": "2400",
                          "available_quality": "2000",
                        },
                        {
                          "symbol": "BABA.US",
                          "symbol_name": "Alibaba",
                          "currency": "US",
                          "quality": "2000209",
                          "available_quality": "2000209",
                        },
                        {
                          "symbol": "2.HK",
                          "symbol_name": "CLP HOLDINGS",
                          "currency": "HK",
                          "quality": "2000",
                          "available_quality": "2000",
                        },
                        {
                          "symbol": "NOK.US",
                          "symbol_name": "Nokia",
                          "currency": "US",
                          "quality": "1",
                          "available_quality": "0",
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  stock_rsp:
    properties:
      list:
        type: "arrary"
        description: "Stock holding information"
        properties:
          account_channel:
            type: string
            description: Account type
          stock_info:
            type: "arrary"
            description: Stock list
            properties:
              symbol:
                type: "string"
                description: Stock code
              symbol_name:
                type: "string"
                description: Stock name
              quality:
                type: "string"
                description: The number of holdings
              available_quality:
                type: "string"
                description: Available quantity
              currency:
                type: "string"
                description: Currency
              cost_price:
                type: "string"
                description: Cost Price(According to the client's choice of average purchase or diluted cost)
