swagger: "2.0"
info:
  description: "該接口用於獲取歷史訂單"
  version: "v1"
  title: "獲取歷史訂單"
paths:
  /v1/trade/order/history:
    get:
      access: "交易權限"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
        - name: "status"
          type: string[]
          in: query
          description: "[訂單狀態](../trade-definition#orderstatus)<br/><br/>例如：`status=FilledStatus&status=NewStatus`"
          required: false
        - name: side
          type: "string"
          in: query
          description: "
            買賣方向<br/><br/>
            **可選值:**<br/>
            `Buy` - 買入<br/>
            `Sell` - 賣出"
          required: false
        - name: market
          type: "string"
          in: query
          description: "
            市場<br/><br/>
            **可選值:**<br/>
            `US` - 美股<br/>
            `HK` - 港股"
          required: false
        - name: "start_at"
          type: "string"
          required: false
          description: "開始時間，格式為時間戳 (秒)，例如：`1650410999`。<br/><br/>開始時間為空時，默認為結束時間或當前時間前九十天。"
        - name: "end_at"
          type: "string"
          required: false
          description: "結束時間，格式為時間戳 (秒)，例如：`1650410999`。<br/><br/>結束時間為空時，默認為開始時間後九十天或當前時間。"
      responses:
        "200":
          description: "歷史訂單查詢成功"
          schema:
            $ref: "#/definitions/history_orders_rsp"
        "400":
          description: "查詢失敗，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          from datetime import datetime
          from longbridge.openapi import TradeContext, Config, OrderStatus, OrderSide, Market

          config = Config.from_env()
          ctx = TradeContext(config)

          resp = ctx.history_orders(
              symbol = "700.HK",
              status = [OrderStatus.Filled, OrderStatus.New],
              side = OrderSide.Buy,
              market = Market.HK,
              start_at = datetime(2022, 5, 9),
              end_at = datetime(2022, 5, 12),
          )
          print(resp)
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "orders":
                [
                  {
                    "currency": "HKD",
                    "executed_price": "0.000",
                    "executed_quantity": "0",
                    "expire_date": "",
                    "last_done": "",
                    "limit_offset": "",
                    "msg": "",
                    "order_id": "706388312699592704",
                    "order_type": "ELO",
                    "outside_rth": "UnknownOutsideRth",
                    "price": "11.900",
                    "quantity": "200",
                    "side": "Buy",
                    "status": "RejectedStatus",
                    "stock_name": "東亞銀行",
                    "submitted_at": "1651644897",
                    "symbol": "23.HK",
                    "tag": "Normal",
                    "time_in_force": "Day",
                    "trailing_amount": "",
                    "trailing_percent": "",
                    "trigger_at": "0",
                    "trigger_price": "",
                    "trigger_status": "NOT_USED",
                    "updated_at": "1651644898",
                    "remark": "",
                  },
                ],
            },
        }
definitions:
  history_orders_rsp:
    required: ["has_more"]
    properties:
      has_more:
        type: boolean
        description: "是否還有更多數據。<br/><br/>每次查詢最大訂單數量為 1000，如果查詢結果數量超過 1000，那麽 has_more 就會為 true"
        required: true
      orders:
        type: "object[]"
        description: 訂單信息
        required:
          [
            "order_id",
            "status",
            "stock_name",
            "quantity",
            "executed_quantity",
            "price",
            "executed_price",
            "submitted_at",
            "side",
            "symbol",
            "order_type",
            "last_done",
            "trigger_price",
            "msg",
            "tag",
            "time_in_force",
            "expire_date",
            "updated_at",
            "trigger_at",
            "trailing_amount",
            "trailing_percent",
            "limit_offset",
            "trigger_status",
            "currency",
            "outside_rth",
            "remark",
          ]
        properties:
          order_id:
            type: "string"
            description: 訂單 ID
            required: true
          status:
            type: "string"
            description: "[訂單狀態](../trade-definition#orderstatus)"
            required: true
          stock_name:
            type: "string"
            description: 股票名稱
            required: true
          quantity:
            type: "string"
            description: 下單數量
            required: true
          executed_quantity:
            type: "string"
            description: 成交數量。<br/><br/>當訂單未成交時為 0
          price:
            type: "string"
            description: 下單價格。<br/><br/>當市價條件單未觸發時為空字符串
            required: true
          executed_price:
            type: "string"
            description: 成交價。<br/><br/>當訂單未成交時為 0
          submitted_at:
            type: "string"
            description: 下單時間
            required: true
          side:
            type: "string"
            description: "
              買賣方向<br/><br/>
              **可選值:**<br/>
              `Buy` - 買入<br/>
              `Sell` - 賣出"
            required: true
          symbol:
            type: "string"
            description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
            required: true
          order_type:
            type: "string"
            description: "[訂單類型](../trade-definition#ordertype)"
            required: true
          last_done:
            type: "string"
            description: 最近成交價格。<br/><br/>當訂單未成交時為空字符串
            required: true
          trigger_price:
            type: "string"
            description: "`LIT` / `MIT` 訂單觸發價格。<br/><br/>當訂單不是 `LIT` / `MIT` 訂單為空字符串"
            required: true
          msg:
            type: "string"
            description: 拒絕信息或備註，默認為空字符串。
            required: true
          tag:
            type: "string"
            description: "訂單標記<br/><br/>
              **可選值:**<br/>
              `Normal` - 普通訂單<br/>
              `GTC` - 長期單<br/>
              `Grey` - 暗盤單"
            required: true
          time_in_force:
            type: "string"
            description: "
              訂單有效期類型<br/><br/>
              **可選值:**<br/>
              `Day` - 當日有效<br/>
              `GTC` - 撤單前有效<br/>
              `GTD` - 到期前有效"
            required: true
          expire_date:
            type: "string"
            required: true
            description: 長期單過期時間，格式為 `YYYY-MM-DD`, 例如：`2022-12-05。<br/><br/>不是長期單時，默認為空字符串。`
          updated_at:
            type: "string"
            required: true
            description: 最近更新時間，格式為時間戳 (秒)，默認為 0。
          trigger_at:
            type: "string"
            required: true
            description: 條件單觸發時間，格式為時間戳 (秒)，默認為 0。
          trailing_amount:
            type: "string"
            required: true
            description: "`TSLPAMT` / `TSMAMT` 訂單跟蹤金額。<br/><br/>當訂單不是 `TSLPAMT` / `TSMAMT` 訂單時為空字符串。"
          trailing_percent:
            type: "string"
            required: true
            description: "`TSLPPCT` / `TSMPCT` 訂單跟蹤漲跌幅。<br/><br/>當訂單不是 `TSLPPCT` / `TSMPCT` 訂單時為空字符串。"
          limit_offset:
            type: "string"
            required: true
            description: "`TSLPAMT` / `TSLPPCT` 訂單指定價差。<br/><br/>當訂單不是 `TSLPAMT` / `TSLPPCT` 訂單時為空字符串。"
          trigger_status:
            type: "string"
            required: true
            description: "條件單觸發狀態<br/>
              當訂單不是條件單或條件單未觸發時, 觸發狀態為 NOT_USED<br/><br/>
              **可選值:**<br/>
              `NOT_USED` - 未激活
              `DEACTIVE` - 已失效
              `ACTIVE` - 已激活
              `RELEASED` - 已觸發"
          currency:
            type: "string"
            description: 結算貨幣
            required: true
          outside_rth:
            type: "string"
            required: true
            description: 是否允許盤前盤後<br/>
              當訂單不是美股時, 默認為 UnknownOutsideRth<br/><br/>
              **可選值:**<br/>
              `RTH_ONLY` - 不允許盤前盤後<br/>
              `ANY_TIME` - 允許盤前盤後"
          remark:
            type: "string"
            description: 備註
            required: true
