swagger: '2.0'
info:
  description: |
    該接口用於修改訂單的價格，數量。

    <SDKLinks module="trade" klass="TradeContext" method="replace_order" />
  version: 'v1'
  title: '修改訂單'
paths:
  /v1/trade/order:
    put:
      access: '交易權限'
      parameters:
        - name: 'order_id'
          type: 'string'
          description: '訂單 ID'
          required: true
        - name: 'quantity'
          type: 'string'
          description: '改單數量，例如：`200`'
          required: true
        - name: 'price'
          required: false
          description: 改單價格，例如：`388.5`<br/><br/>
            `LO` / `ELO` / `ALO` / `ODD` / `LIT` 訂單必填
        - name: trigger_price
          required: false
          description: 觸發價格，例如：`388.5`<br/><br/>
            `LIT` / `MIT` 訂單必填
        - name: limit_offset
          required: false
          description: 指定價差<br/><br/>
            `TSLPAMT` / `TSLPPCT` 訂單必填
        - name: trailing_amount
          required: false
          description: 跟蹤金額<br/><br/>
            `TSLPAMT` 訂單必填
        - name: trailing_percent
          required: false
          description: 跟蹤漲跌幅<br/><br/>
            `TSLPPCT` 訂單必填
        - name: remark
          required: false
          description: '備註 (最大 64 字符)'
      responses:
        '200':
          description: '提交成功，訂單已委托。'
        '400':
          description: '下單被拒絕，請求參數錯誤。'
      request_body:
        type: 'python'
        value: |
          from decimal import Decimal
          from longport.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)

          ctx.replace_order(
              order_id = "709043056541253632",
              quantity = 100,
              price = Decimal("100"),
          )
      response_body: { 'code': 0, 'message': 'success', 'data': {} }
