swagger: "2.0"
info:
  description: "該接口用於獲取當日訂單和訂單查詢"
  version: "v1"
  title: "獲取當日訂單"
paths:
  /v1/trade/order/today:
    get:
      access: "交易權限"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
        - name: "status"
          type: string[]
          in: query
          description: "[訂單狀態](../trade-definition#orderstatus)<br/><br/>例如：`status=FilledStatus&status=NewStatus`"
          required: false
        - name: side
          type: "string"
          in: query
          description: 買賣方向<br/><br/>
            **可選值:**<br/>
            `Buy` - 買入<br/>
            `Sell` - 賣出
          required: false
        - name: market
          type: "string"
          in: query
          description: 市場<br/><br/>
            **可選值:**<br/>
            `US` - 美股<br/>
            `HK` - 港股
          required: false
        - name: "order_id"
          type: "string"
          required: false
          description: "訂單 ID，用於指定訂單 ID 查詢，例如：`701276261045858304`"
      responses:
        "200":
          description: "當日訂單查詢成功"
          schema:
            $ref: "#/definitions/today_orders_rsp"
        "400":
          description: "查詢失敗，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          from longbridge.openapi import TradeContext, Config, OrderStatus, OrderSide, Market

          config = Config.from_env()
          ctx = TradeContext(config)

          resp = ctx.today_orders(
              symbol = "700.HK",
              status = [OrderStatus.Filled, OrderStatus.New],
              side = OrderSide.Buy,
              market = Market.HK,
          )
          print(resp)
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "orders":
                [
                  {
                    "currency": "HKD",
                    "executed_price": "0.000",
                    "executed_quantity": "0",
                    "expire_date": "",
                    "last_done": "",
                    "limit_offset": "",
                    "msg": "",
                    "order_id": "706388312699592704",
                    "order_type": "ELO",
                    "outside_rth": "UnknownOutsideRth",
                    "price": "11.900",
                    "quantity": "200",
                    "side": "Buy",
                    "status": "RejectedStatus",
                    "stock_name": "東亞銀行",
                    "submitted_at": "1651644897",
                    "symbol": "23.HK",
                    "tag": "Normal",
                    "time_in_force": "Day",
                    "trailing_amount": "",
                    "trailing_percent": "",
                    "trigger_at": "0",
                    "trigger_price": "",
                    "trigger_status": "NOT_USED",
                    "updated_at": "1651644898",
                    "remark": "",
                  },
                ],
            },
        }
definitions:
  today_orders_rsp:
    properties:
      orders:
        type: "object[]"
        description: 订单信息
        required:
          [
            "order_id",
            "status",
            "stock_name",
            "quantity",
            "executed_quantity",
            "price",
            "executed_price",
            "submitted_at",
            "side",
            "symbol",
            "order_type",
            "last_done",
            "trigger_price",
            "msg",
            "tag",
            "time_in_force",
            "expire_date",
            "updated_at",
            "trigger_at",
            "trailing_amount",
            "trailing_percent",
            "limit_offset",
            "trigger_status",
            "currency",
            "outside_rth",
            "remark",
          ]
        properties:
          order_id:
            type: "string"
            description: 订单 ID
            required: true
          status:
            type: "string"
            description: "[订单状态](../trade-definition#orderstatus)"
            required: true
          stock_name:
            type: "string"
            description: 股票名称
            required: true
          quantity:
            type: "string"
            description: 下单数量
            required: true
          executed_quantity:
            type: "string"
            description: 成交数量。<br/><br/>当订单未成交时为 0
          price:
            type: "string"
            description: 下单价格。<br/><br/>当市价条件单未触发时为空字符串
            required: true
          executed_price:
            type: "string"
            description: 成交价。<br/><br/>当订单未成交时为 0
          submitted_at:
            type: "string"
            description: 下单时间
            required: true
          side:
            type: "string"
            description: "
              买卖方向<br/><br/>
              **可选值:**<br/>
              `Buy` - 买入<br/>
              `Sell` - 卖出"
            required: true
          symbol:
            type: "string"
            description: "股票代码，使用 `ticker.region` 格式，例如：`AAPL.US`"
            required: true
          order_type:
            type: "string"
            description: "[订单类型](../trade-definition#ordertype)"
            required: true
          last_done:
            type: "string"
            description: 最近成交价格。<br/><br/>当订单未成交时为空字符串
            required: true
          trigger_price:
            type: "string"
            description: "`LIT` / `MIT` 订单触发价格。<br/><br/>当订单不是 `LIT` / `MIT` 订单为空字符串"
            required: true
          msg:
            type: "string"
            description: 拒绝信息或备注，默认为空字符串。
            required: true
          tag:
            type: "string"
            description: "订单标记<br/><br/>
              **可选值:**<br/>
              `Normal` - 普通订单<br/>
              `GTC` - 长期单<br/>
              `Grey` - 暗盘单"
            required: true
          time_in_force:
            type: "string"
            description: "
              订单有效期类型<br/><br/>
              **可选值:**<br/>
              `Day` - 当日有效<br/>
              `GTC` - 撤单前有效<br/>
              `GTD` - 到期前有效"
            required: true
          expire_date:
            type: "string"
            required: true
            description: 长期单过期时间，格式为 `YYYY-MM-DD`, 例如：`2022-12-05。<br/><br/>不是长期单时，默认为空字符串。`
          updated_at:
            type: "string"
            required: true
            description: 最近更新时间，格式为时间戳 (秒)，默认为 0。
          trigger_at:
            type: "string"
            required: true
            description: 条件单触发时间，格式为时间戳 (秒)，默认为 0。
          trailing_amount:
            type: "string"
            required: true
            description: "`TSLPAMT` / `TSMAMT` 订单跟踪金额。<br/><br/>当订单不是 `TSLPAMT` / `TSMAMT` 订单时为空字符串。"
          trailing_percent:
            type: "string"
            required: true
            description: "`TSLPPCT` / `TSMPCT` 订单跟踪涨跌幅。<br/><br/>当订单不是 `TSLPPCT` / `TSMPCT` 订单时为空字符串。"
          limit_offset:
            type: "string"
            required: true
            description: "`TSLPAMT` / `TSLPPCT` 订单指定价差。<br/><br/>当订单不是 `TSLPAMT` / `TSLPPCT` 订单时为空字符串。"
          trigger_status:
            type: "string"
            required: true
            description: "条件单触发状态<br/>
              当订单不是条件单或条件单未触发时, 触发状态为 NOT_USED<br/><br/>
              **可选值:**<br/>
              `NOT_USED` - 未激活
              `DEACTIVE` - 已失效
              `ACTIVE` - 已激活
              `RELEASED` - 已触发"
          currency:
            type: "string"
            description: 结算货币
            required: true
          outside_rth:
            type: "string"
            required: true
            description: 是否允许盘前盘后<br/>
              当订单不是美股时, 默认为 UnknownOutsideRth<br/><br/>
              **可选值:**<br/>
              `RTH_ONLY` - 不允许盘前盘后<br/>
              `ANY_TIME` - 允许盘前盘后"
          remark:
            type: "string"
            description: 備註
            required: true
