swagger: "2.0"
info:
  description: "該接口用於訂單撤銷"
  version: "v1"
  title: "撤銷訂單"
paths:
  /v1/trade/order:
    delete:
      access: "交易權限"
      parameters:
        - name: "order_id"
          type: "string"
          description: "訂單 ID"
          required: true
      responses:
        "200":
          description: "提交成功，訂單已委托。"
        "400":
          description: "撤單被拒絕，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridgeapp.com"))

          query = {
              "order_id": "709043056541253632",
          }

          try:
            resp = http.delete("/v1/trade/order", query=query)
            print(json.dumps(resp.data, indent=2))
          except Exception as e:
            print(f"Submit order error\ncode: {e.code}\nmessage: {e.message}")
      response_body: { "code": 0, "message": "success", "data": {} }
