swagger: "2.0"
info:
  description: "該接口用於訂單撤銷"
  version: "v1"
  title: "撤銷訂單"
paths:
  /v1/trade/order:
    delete:
      access: "交易權限"
      parameters:
        - name: "order_id"
          type: "string"
          description: "訂單 ID"
          required: true
      responses:
        "200":
          description: "提交成功，訂單已委托。"
        "400":
          description: "撤單被拒絕，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          from longbridge.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)

          ctx.cancel_order("709043056541253632")
      response_body: { "code": 0, "message": "success", "data": {} }
