swagger: "2.0"
info:
  description: "該接口用於獲取用戶每個幣種可用、可取、凍結、待結算金額、在途資金 (基金申購贖回) 信息"
  version: "v1"
  title: "獲取賬戶資金"
paths:
  /v1/asset/account:
    get:
      access:
      parameters:
        - name: "currency"
          type: "string"
          description: 幣種（HKD、USD、CNH）
          required: false
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/accountcash_rsp"
        "400":
          description: "內部錯誤"
      request_body:
        type: "python"
        value: |
          # 獲取賬戶資金
          # https://open.longportapp.com/docs/trade/asset/account
          from longbridge.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)
          resp = ctx.account_balance()
          print(resp)
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "total_cash": "1759070010.72",
                    "max_finance_amount": "977582000",
                    "remaining_finance_amount": "0",
                    "risk_level": "1",
                    "margin_call": "2598051051.50",
                    "currency": "HKD",
                    "net_assets": "24145.90",
                    "init_margin": "1540.09",
                    "maintenance_margin": "1540.09"
                    "cash_infos":
                      [
                        {
                          "withdraw_cash": "97592.30",
                          "available_cash": "195902464.37",
                          "frozen_cash": "11579339.13",
                          "settling_cash": "207288537.81",
                          "currency": "HKD",
                        },
                        {
                          "withdraw_cash": "199893416.74",
                          "available_cash": "199893416.74",
                          "frozen_cash": "28723.76",
                          "settling_cash": "-276806.51",
                          "currency": "USD",
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  accountcash_rsp:
    properties:
      list:
        type: "object[]"
        description: 賬戶資金信息
        required:
          - total_cash
          - max_finance_amount
          - remaining_finance_amount
          - risk_level
          - margin_call
          - currency
          - net_assets
          - init_margin
          - maintenance_margin
        properties:
          total_cash:
            type: "string"
            description: 現金總額
            required: true
          max_finance_amount:
            type: "string"
            description: 最大融資金額
            required: true
          remaining_finance_amount:
            type: "string"
            description: 剩餘融資金額
            required: true
          risk_level:
            type: "string"
            description: 風控等級  <br/> <br/> <b>可選值:</b><br/> `0` - 安全  <br/> `1` - 中風險<br/> `2` - 預警<br/> `3` - 危險
            required: true
          margin_call:
            type: "string"
            description: 追繳保證金
            required: true
          net_assets:
            type: "string"
            description: 淨資產
            required: true
          init_margin:
            type: "string"
            description: 初始保證金
            required: true
          maintenance_margin:
            type: "string"
            description: 維持保證金
            required: true
          currency:
            type: "string"
            description: 幣種
            required: true
          cash_infos:
            type: "object[]"
            description: 現金詳情
            required:
              - currency
              - withdraw_cash
              - available_cash
              - frozen_cash
              - settling_cash
            properties:
              withdraw_cash:
                type: "string"
                description: 可提現金
                required: true
              available_cash:
                type: "string"
                description: 可用現金
                required: true
              frozen_cash:
                type: "string"
                description: 凍結現金
                required: true
              settling_cash:
                type: "string"
                description: 待結算現金
                required: true
              currency:
                type: "string"
                description: 幣種
                required: true
