swagger: "2.0"
info:
  description: "Create watched group"
  version: "v1"
  title: "Create watched group"
paths:
  /v1/watchlist/groups:
    post:
      access:
      parameters:
        - name: "name"
          type: "string"
          in: body
          description: "Group name"
          required: true
        - name: "securities"
          type: "string[]"
          in: body
          description: "Returns securities list under the group. The order in the list will be used as the presentation order."
          required: false

      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/create_group_response"
        "500":
          description: "Internal error"
      request_body:
        type: "python"
        value: |

      response_body: { "code": 0, "data": { "id": 10086 } }

definitions:
  create_group_response:
    properties:
      id:
        type: "integer"
        description: Group ID
        required: true
