swagger: "2.0"
info:
  description: "Update watched group"
  version: "v1"
  title: "Update watched group"
paths:
  /v1/watchlist/groups:
    put:
      access:
      parameters:
        - name: "id"
          type: "integer"
          in: body
          description: "Group ID"
          required: true
        - name: "name"
          type: "string"
          in: body
          description: "Group name. No update if not passed."
          required: false
        - name: "securities"
          type: "string[]"
          in: body
          description: "Securities list under the group. No update if not passed. The order in the list will be used as the presentation order. Securities in the group that are not in this list will be removed from watch list"
          required: false

      responses:
        "200":
          description: "Success"
        "500":
          description: "Internal error"
      request_body:
        type: "python"
        value: |

      response_body: { "code": 0 }
