swagger: "2.0"
info:
  description: "Update watched group"
  version: "v1"
  title: "Update watched group"
paths:
  /v1/watchlist/groups:
    put:
      access:
      parameters:
        - name: "id"
          type: "integer"
          description: "Group ID"
          required: true
        - name: "name"
          type: "string"
          description: "Group name"
          required: true

      responses:
        "200":
          description: "Success"
        "500":
          description: "Internal error"
      request_body:
        type: "python"
        value: |

      response_body: { "code": 0 }
