swagger: "2.0"
info:
  description: "该接口用于订单详情查询"
  version: "v1"
  title: "订单详情"
paths:
  /v1/trade/order:
    get:
      access: "交易权限"
      parameters:
        - name: "order_id"
          type: "string"
          description: "订单 ID，用于指定订单 ID 查询，例如：`701276261045858304`"
          required: true
      responses:
        "200":
          description: "订单详情查询成功"
          schema:
            $ref: "#/definitions/order_detail_rsp"
        "400":
          description: "查询失败，请求参数错误。"
      request_body:
        type: "python"
        value: |
          from longbridge.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)

          resp = ctx.order_detail(
              order_id = "701276261045858304",
          )
          print(resp)
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "order_id": "828911589593341952",
              "status": "ReplacedStatus",
              "stock_name": "腾讯控股 1",
              "quantity": "200",
              "executed_quantity": "0",
              "price": "381.000",
              "executed_price": "0.000",
              "submitted_at": "1680856723",
              "side": "Buy",
              "symbol": "700.HK",
              "order_type": "LO",
              "last_done": "381.000",
              "trigger_price": "0.000",
              "msg": "",
              "tag": "Normal",
              "time_in_force": "Day",
              "expire_date": "2023-04-11",
              "updated_at": "1680856746",
              "trigger_at": "0",
              "trailing_amount": "",
              "trailing_percent": "",
              "limit_offset": "",
              "trigger_status": "NOT_USED",
              "outside_rth": "UnknownOutsideRth",
              "currency": "HKD",
              "remark": "",
              "free_status": 0,
              "free_amount": "",
              "free_currency": "",
              "deductions_status": 0,
              "deductions_amount": "",
              "deductions_currency": "",
              "platform_deducted_status": 0,
              "platform_deducted_amount": "",
              "platform_deducted_currency": "",
              "history":
                [
                  {
                    "price": "381.0000",
                    "quantity": "200",
                    "status": "ReplacedStatus",
                    "msg": "",
                    "time": "1680856746",
                  },
                  {
                    "price": "400.0000",
                    "quantity": "100",
                    "status": "NewStatus",
                    "msg": "",
                    "time": "1680856723",
                  },
                ],
              "charge_detail":
                {
                  "items":
                    [
                      { "code": 1, "name": "收费明细", "fees": [] },
                      { "code": 2, "name": "第三方收费明细", "fees": [] },
                    ],
                  "total_amount": "0.00",
                  "currency": "HKD",
                },
            },
        }
definitions:
  order_detail_rsp:
    type: "object"
    description: 订单信息
    required:
      [
        "order_id",
        "status",
        "stock_name",
        "quantity",
        "executed_quantity",
        "price",
        "executed_price",
        "submitted_at",
        "side",
        "symbol",
        "order_type",
        "last_done",
        "trigger_price",
        "msg",
        "tag",
        "time_in_force",
        "expire_date",
        "updated_at",
        "trigger_at",
        "trailing_amount",
        "trailing_percent",
        "limit_offset",
        "trigger_status",
        "currency",
        "outside_rth",
        "remark",
        "free_status",
        "free_amount",
        "free_currency",
        "deductions_status",
        "deductions_amount",
        "deductions_currency",
        "platform_deducted_status",
        "platform_deducted_amount",
        "platform_deducted_currency",
        "history",
        "charge_detail",
      ]
    properties:
      order_id:
        type: "string"
        description: 订单 ID
        required: true
      status:
        type: "string"
        description: "[订单状态](../trade-definition#orderstatus)"
        required: true
      stock_name:
        type: "string"
        description: 股票名称
        required: true
      quantity:
        type: "string"
        description: 下单数量
        required: true
      executed_quantity:
        type: "string"
        description: 成交数量。<br/><br/>当订单未成交时为 0
      price:
        type: "string"
        description: 下单价格。<br/><br/>当市价条件单未触发时为空字符串
        required: true
      executed_price:
        type: "string"
        description: 成交价。<br/><br/>当订单未成交时为 0
      submitted_at:
        type: "string"
        description: 下单时间
        required: true
      side:
        type: "string"
        description: "
          买卖方向<br/><br/>
          **可选值:**<br/>
          `Buy` - 买入<br/>
          `Sell` - 卖出"
        required: true
      symbol:
        type: "string"
        description: "股票代码，使用 `ticker.region` 格式，例如：`AAPL.US`"
        required: true
      order_type:
        type: "string"
        description: "[订单类型](../trade-definition#ordertype)"
        required: true
      last_done:
        type: "string"
        description: 最近成交价格。<br/><br/>当订单未成交时为空字符串
        required: true
      trigger_price:
        type: "string"
        description: "`LIT` / `MIT` 订单触发价格。<br/><br/>当订单不是 `LIT` / `MIT` 订单为空字符串"
        required: true
      msg:
        type: "string"
        description: 拒绝信息或备注，默认为空字符串。
        required: true
      tag:
        type: "string"
        description: "订单标记<br/><br/>
          **可选值:**<br/>
          `Normal` - 普通订单<br/>
          `GTC` - 长期单<br/>
          `Grey` - 暗盘单"
        required: true
      time_in_force:
        type: "string"
        description: "
          订单有效期类型<br/><br/>
          **可选值:**<br/>
          `Day` - 当日有效<br/>
          `GTC` - 撤单前有效<br/>
          `GTD` - 到期前有效"
        required: true
      expire_date:
        type: "string"
        required: true
        description:
          "长期单过期时间，格式为 `YYYY-MM-DD`, 例如：`2022-12-05。<br/><br/>
          不是长期单时，默认为空字符串。"
      updated_at:
        type: "string"
        required: true
        description: 最近更新时间，格式为时间戳 (秒)，默认为 0。
      trigger_at:
        type: "string"
        required: true
        description: 条件单触发时间，格式为时间戳 (秒)，默认为 0。
      trailing_amount:
        type: "string"
        required: true
        description: "`TSLPAMT` / `TSMAMT` 订单跟踪金额。<br/><br/>当订单不是 `TSLPAMT` / `TSMAMT` 订单时为空字符串。"
      trailing_percent:
        type: "string"
        required: true
        description: "`TSLPPCT` / `TSMPCT` 订单跟踪涨跌幅。<br/><br/>当订单不是 `TSLPPCT` / `TSMPCT` 订单时为空字符串。"
      limit_offset:
        type: "string"
        required: true
        description: "`TSLPAMT` / `TSLPPCT` 订单指定价差。<br/><br/>当订单不是 `TSLPAMT` / `TSLPPCT` 订单时为空字符串。"
      trigger_status:
        type: "string"
        required: true
        description: "条件单触发状态<br/>
          当订单不是条件单或条件单未触发时, 触发状态为 NOT_USED<br/><br/>
          **可选值:**<br/>
          `NOT_USED` - 未激活<br/>
          `DEACTIVE` - 已失效<br/>
          `ACTIVE` - 已激活<br/>
          `RELEASED` - 已触发"
      currency:
        type: "string"
        description: 结算货币
        required: true
      outside_rth:
        type: "string"
        required: true
        description: 是否允许盘前盘后<br/>
          当订单不是美股时, 默认为 UnknownOutsideRth<br/><br/>
          **可选值:**<br/>
          `RTH_ONLY` - 不允许盘前盘后<br/>
          `ANY_TIME` - 允许盘前盘后
      remark:
        type: "string"
        description: 备注
        required: true
      free_status:
        type: "string"
        required: true
        description: 免佣状态，默认为 None<br/><br/>
          **可选值:**<br/>
          `None` - 无<br/>
          `Calculated` - 免佣额待计算<br/>
          `Pending` - 待免佣<br/>
          `Ready` - 已免佣
      free_amount:
        type: "string"
        required: true
        description: 免佣金额，默认为空字符串
      free_currency:
        type: "string"
        required: true
        description: 免佣货币，默认为空字符串
      deductions_status:
        type: "string"
        required: true
        description: 抵扣状态/返现状态，默认为 NONE<br/><br/>
          **可选值:**<br/>
          `NONE` - 待结算 <br/>
          `NO_DATA` - 已结算无数据<br/>
          `PENDING` - 已结算待发放<br/>
          `DONE` - 已结算已发放
      deductions_amount:
        type: "string"
        required: true
        description: 抵扣金额，默认为空字符串
      deductions_currency:
        type: "string"
        required: true
        description: 抵扣货币，默认为空字符串
      platform_deducted_status:
        type: "string"
        required: true
        description: 平台费抵扣状态/返现状态，默认为 NONE<br/><br/>
          **可选值:**<br/>
          `NONE` - 待结算 <br/>
          `NO_DATA` - 已结算无数据<br/>
          `PENDING` - 已结算待发放<br/>
          `DONE` - 已结算已发放
      platform_deducted_amount:
        type: "string"
        required: true
        description: 平台费抵扣金额，默认为空字符串
      platform_deducted_currency:
        type: "string"
        required: true
        description: 平台费抵扣货币，默认为空字符串
      history:
        type: "object[]"
        description: 订单历史明细
        required:
          - price
          - quantity
          - status
          - msg
          - time
        properties:
          price:
            type: "string"
            description: 成交展示成交价格，过期、撤单、拒绝等状态展示提交价格
            required: true
          quantity:
            type: "string"
            description: 成交展示成交数量，过期、撤单、拒绝等状态展示剩余数量
            required: true
          status:
            type: "string"
            description: 订单状态
            required: true
          msg:
            type: "string"
            description: 成交或错误信息
            required: true
          time:
            type: "string"
            description: 发生时间
            required: true
      charge_detail:
        type: "object"
        description: 订单费用
        required:
          - items
          - total_amount
          - currency
        properties:
          total_amount:
            type: "string"
            description: 全部费用
            required: true
          currency:
            type: "string"
            description: 结算货币
            required: true
          items:
            type: "object[]"
            description: 订单费用明细
            required:
              - code
              - name
              - fees
            properties:
              code:
                type: "string"
                description: 收费类别代码<br/><br/>
                  **可选值:**<br/>
                  `UNKNOWN`<br/>
                  `BROKER_FEES`<br/>
                  `THIRD_FEES`
              name:
                type: "string"
                description: 收费类别名称
              fees:
                type: "object[]"
                description: 收费明细
                required:
                  - code
                  - name
                  - amount
                  - currency
                properties:
                  code:
                    type: "string"
                    description: 收费代码
                    required: true
                  name:
                    type: "string"
                    description: 收费名称
                    required: true
                  amount:
                    type: "string"
                    description: 单项收费金额
                    required: true
                  currency:
                    type: "string"
                    description: 收费货币
                    required: true
