swagger: '2.0'
info:
  description: |
    创建自选股分组

    <SDKLinks module="quote" klass="QuoteContext" method="create_watchlist_group" />
  version: 'v1'
  title: '创建自选股分组'
paths:
  /v1/watchlist/groups:
    post:
      access:
      parameters:
        - name: 'name'
          type: 'string'
          description: '分组名称，例如 `信息产业组`'
          required: true
        - name: 'securities'
          type: 'string[]'
          description: '股票列表，例如 `["BABA.US","AAPL.US"]`<br />
            分组下股票的展示顺序，与此列表的顺序一致<br />
            如果不传此参数，则创建一个空的分组'
          required: false

      responses:
        '200':
          description: '返回成功'
          schema:
            $ref: '#/definitions/create_group_response'
        '500':
          description: '内部错误'
      request_body:
        type: 'python'
        value: |
          from longport.openapi import QuoteContext, Config

          config = Config.from_env()
          ctx = QuoteContext(config)
          group_id = ctx.create_watchlist_group(name = "Watchlist1", securities = ["700.HK", "AAPL.US"])
          print(group_id)

      response_body: { 'code': 0, 'data': { 'id': 10086 } }

definitions:
  create_group_response:
    properties:
      id:
        type: 'integer'
        description: 分组 ID
        required: true
