swagger: "2.0"
info:
  description: "更新关注分组下的股票"
  version: "v1"
  title: "更新关注分组下的股票"
paths:
  /v1/watchlist/group_securities:
    put:
      access:
      parameters:
        - name: "id"
          type: "integer"
          description: "分组 ID"
          required: true
        - name: "securities"
          type: "string[]"
          description: "股票列表"
          required: true

      responses:
        "200":
          description: "返回成功"
        "500":
          description: "内部错误"
      request_body:
        type: "python"
        value: |

      response_body: { "code": 0 }
