swagger: "2.0"
info:
  description: "删除关注分组"
  version: "v1"
  title: "删除关注分组"
paths:
  /v1/watchlist/groups:
    delete:
      access:
      parameters:
        - name: "id"
          type: "integer"
          in: query
          description: "分组 ID"
          required: true
        - name: "purge"
          type: "boolean"
          in: query
          description: "是否清除分组下的股票。如果不清除，股票会展示在全部分组"
          required: true

      responses:
        "200":
          description: "返回成功"
        "500":
          description: "内部错误"
      request_body:
        type: "python"
        value: |

      response_body: { "code": 0 }
