swagger: "2.0"
info:
  description: "订单接口提供完整的下单、取消下单等功能。"
  version: "v1"
  title: "委托订单"
paths:
  /v1/trade/order/submit:
    post:
      summary: "委托下单"
      description: "港美股，窝轮，期权委托下单"
      access: "交易权限"
      parameters:
        - name: "symbol"
          type: "string"
          description: "股票代码，使用 `ticker.region`` 格式，例如：`AAPL.US`"
          required: true
        - name: "order_type"
          type: "string"
          description: "订单类型，例如：`LO`，详见：[OrderType](../trade-definition#ordertype)"
          required: true
        - name: "submitted_price"
          required: true
          description: 下单价格（LO / ELO /  ALO /  ODD / LIT 订单必填，其他可以选填），例如：`388.5`
        - name: "submitted_quantity"
          required: true
          description: 下单数量，例如：`100`
        - name: trigger_price
          description: 触发价格（LIT / MIT 订单必填），例如：`388.5`
        - name: limit_offset
          description: 指定价差 (TSLPAMT / TSLPPCT 订单必填)
        - name: trailing_amount
          description: 跟踪金额 (TSLPAMT / TSMAMT 订单必填)
        - name: trailing_percent
          description: 跟踪百分比 (TSLPPCT / TSMAPCT 订单必填)
        - name: expire_date
          description: 长期单过期时间 (time_in_force 为 GTD 时必填)，格式为 `YYYY-MM-DD`，例如：`2022-12-05`
        - name: side
          type: "string"
          description: "订单方向，买卖方向<br/><br/>Buy - 买入<br/>Sell - 卖出"
          required: true
        - name: outside_rth
          description: "美股 (美股订单必填) 是否允许盘前盘后<br/><br/>RTH_ONLY - 不允许盘前盘后<br/>ANY_TIME - 允许盘前盘后"
        - name: time_in_force
          required: true
          description: "订单有效期类型<br/><br/>Day:当日有效<br/>GTC - 撤单前有效<br/>GTD - 到期前有效"
        - name: remark
          description: "备注 (最大 64 字符)"
      responses:
        "200":
          description: "提交成功，订单已委托。"
        "401":
          description: "下单被拒绝，资金不足。"
      request_body:
        type: "python"
        value: |
          def example():
            # TODO
      response_body: { "code": 0, "data": { "order_id": 683615454870679552 } }
