swagger: '2.0'
info:
  description: |
    该接口用于获取包括账户、基金代码、持有份额、成本净值、当前净值、币种在内的基金持仓信息。

    <SDKLinks module="trade" klass="TradeContext" method="fund_positions" />
  version: 'v1'
  title: '获取基金持仓'
paths:
  /v1/asset/fund:
    get:
      access:
      parameters:
        - name: 'symbol'
          type: 'string[]'
          description: 基金代码，使用 `ISIN` 格式，例如：`HK0000676327` <a href="https://en.wikipedia.org/wiki/International_Securities_Identification_Number">ISIN 解释</a>
          required: false
      responses:
        '200':
          description: '返回成功'
          schema:
            $ref: '#/definitions/fund_rsp'
        '400':
          description: '内部错误'
      request_body:
        type: 'python'
        value: |
          # 获取基金持仓
          # https://open.longportapp.com/docs/trade/asset/fund
          from longport.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)
          resp = ctx.fund_positions()
          print(resp)
      response_body:
        {
          'code': 0,
          'data':
            {
              'list':
                [
                  {
                    'account_channel': 'lb',
                    'fund_info':
                      [
                        {
                          'symbol': 'HK0000447943',
                          'symbol_name': '高腾亚洲收益基金',
                          'currency': 'USD',
                          'holding_units': '5.000',
                          'current_net_asset_value': '0',
                          'cost_net_asset_value': '0.00',
                          'net_asset_value_day': '1649865600',
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  fund_rsp:
    properties:
      list:
        type: 'object[]'
        description: '股票持仓信息'
        required:
          - account_channel
        properties:
          account_channel:
            type: string
            description: 账户类型
            required: true
          fund_info:
            type: 'object[]'
            description: 基金详情
            required:
              - symbol
              - current_net_asset_value
              - net_asset_value_day
              - symbol_name
              - currency
              - cost_net_asset_value
            properties:
              symbol:
                type: 'string'
                description: 基金 ISIN 代码
                required: true
              current_net_asset_value:
                type: 'string'
                description: 当前净值
                required: true
              net_asset_value_day:
                type: 'string'
                description: 当前净值时间
                required: true
              symbol_name:
                type: 'string'
                description: 基金名称
                required: true
              currency:
                type: 'string'
                description: 币种
                required: true
              cost_net_asset_value:
                type: 'string'
                description: 成本净值
                required: true
