swagger: "2.0"
info:
  description: "該接口用於獲取歷史訂單的成交明細"
  version: "v1"
  title: "獲取歷史成交明細"
paths:
  /v1/trade/execution/history:
    get:
      access: "交易權限"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
        - name: "start_at"
          type: "string"
          in: query
          required: false
          description: "開始時間，格式為時間戳 (秒)，例如：`1650410999`。<br/><br/>開始時間為空時，默認為結束時間或當前時間前九十天。"
        - name: "end_at"
          type: "string"
          required: false
          description: "結束時間，格式為時間戳 (秒)，例如：`1650410999`。<br/><br/>結束時間為空時，默認為開始時間後九十天或當前時間。"
      responses:
        "200":
          description: "查詢成功"
          schema:
            $ref: "#/definitions/history_executions_rsp"
        "400":
          description: "查詢失敗，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          from datetime import datetime
          from longbridge.openapi import TradeContext, Config

          config = Config.from_env()
          ctx = TradeContext(config)

          resp = ctx.history_executions(
              symbol = "700.HK",
              start_at = datetime(2022, 5, 9),
              end_at = datetime(2022, 5, 12),
          )
          print(resp)
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "has_more": false,
              "trades":
                [
                  {
                    "order_id": "693664675163312128",
                    "price": "388",
                    "quantity": "100",
                    "symbol": "700.HK",
                    "trade_done_at": "1648611351",
                    "trade_id": "693664675163312128-1648611351433741210",
                  },
                ],
            },
        }
definitions:
  history_executions_rsp:
    required: ["has_more"]
    properties:
      has_more:
        type: boolean
        description: "是否還有更多數據。<br/><br/>每次查詢最大訂單數量為 1000，如果查詢結果數量超過 1000，那麽 has_more 就會為 true"
        required: true
      trades:
        type: "object[]"
        description: 成交明細信息
        required:
          [
            "order_id",
            "trade_id",
            "symbol",
            "trade_done_at",
            "quantity",
            "price",
          ]
        properties:
          order_id:
            type: "string"
            description: 訂單 ID
            required: true
          trade_id:
            type: "string"
            description: 成交 ID
            required: true
          symbol:
            type: "string"
            description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
            required: true
          trade_done_at:
            type: "string"
            description: "成交時間，格式為時間戳 (秒)"
            required: true
          quantity:
            type: "string"
            description: 成交數量
            required: true
          price:
            type: "string"
            description: 成交價格
            required: true
