name: Build
on:
  pull_request:
  push:
    branches:
      - '!main'
      - '!canary'
jobs:
  build:
    name: Build Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Bun Install
        run: bun install

      - name: Build Canary
        run: |
          bun run build:canary
