name: Deploy New Version
on:
  push:
    branches:
      - main
      - new-version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_release:
    name: build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download ossutils zip
        run: |
          wget https://github.com/aliyun/ossutil/releases/download/v1.7.17/ossutil-v1.7.17-linux-amd64.zip
          unzip ossutil-v1.7.17-linux-amd64.zip && cp ./ossutil-v1.7.17-linux-amd64/ossutil ${{github.workspace}}/ && chmod +x ${{github.workspace}}/ossutil

      - name: Test ossutil
        run: |
          ${{github.workspace}}/ossutil --version

      - uses: oven-sh/setup-bun@v2

      - name: Install dependency
        run: bun install

      - name: Build release
        run: bun run docs:build

      - name: Upload to Aliyun OSS
        run: |
          ${{github.workspace}}/ossutil cp ./packages/docs/.vitepress/dist oss://lb-assets/github/release/open.longportapp.com/new-docs/raw/ -u -r -j 10 -e oss-cn-hangzhou.aliyuncs.com -i ${{ secrets.FE_LB_ASSET_ACCESS_KEY_ID }} -k ${{ secrets.FE_LB_ASSET_ACCESS_KEY_SECRET }} --include "*.md" --meta=Content-Type:text/markdown\;charset=utf-8,Cache-Control:no-cache
