name: Deploy Release
on:
  push:
    branches:
      - main
      - release
jobs:
  deploy_release:
    name: build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Download ossutils zip
        run: |
          wget https://github.com/aliyun/ossutil/releases/download/v1.7.17/ossutil-v1.7.17-linux-amd64.zip
          unzip ossutil-v1.7.17-linux-amd64.zip && cp ./ossutil-v1.7.17-linux-amd64/ossutil ${{github.workspace}}/ && chmod +x ${{github.workspace}}/ossutil

      - name: Test ossutil cli is ok
        run: |
          ${{github.workspace}}/ossutil --version

      - name: Bun Install
        run: bun install

      - name: Build
        run: bun run build:release

      - name: upload canary dist to oss
        run: |
          ${{github.workspace}}/ossutil cp dist/ oss://lb-assets/github/release/open.longportapp.com/docs/ -u -r -j 10 -e oss-cn-hangzhou.aliyuncs.com -i ${{ secrets.FE_LB_ASSET_ACCESS_KEY_ID }} -k ${{ secrets.FE_LB_ASSET_ACCESS_KEY_SECRET }} --exclude "*.html" --meta=Cache-Control:max-age=31536000
          ${{github.workspace}}/ossutil cp dist/ oss://lb-assets/github/release/open.longportapp.com/docs/ -u -r -j 10 -e oss-cn-hangzhou.aliyuncs.com -i ${{ secrets.FE_LB_ASSET_ACCESS_KEY_ID }} -k ${{ secrets.FE_LB_ASSET_ACCESS_KEY_SECRET }} --include "*.html" --meta=Cache-Control:no-cache
